name: Sync with upstream

on:
  schedule:
    - cron: "0 6 * * *"   # runs daily at 06:00 UTC
  workflow_dispatch:       # allow manual “Run workflow” in UI

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/humanlayer/humanlayer.git || true
          git fetch upstream

      - name: Merge upstream/main into main
        run: |
          git checkout main
          git merge --ff-only upstream/main || echo "Non-fast-forward; manual resolution needed"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main || echo "Push failed (likely due to conflicts)"
